on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    name: 部署到GitHub Pages
    steps:
      - name: 拉取代码
        id: checkout
        uses: actions/checkout@v4
      - name: 编译文档
        run: |
          npm ci
          npm run build
      - name: 部署到gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
      - name: 压缩文档
        run: zip -r docs.zip docs
      - name: 发布草稿
        uses: softprops/action-gh-release@v2
        with:
          files: docs.zip
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
